server:
    port: 8081
    compression:
        enabled: true
        mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
    
info:
    app:
        description: Spring Boot Geospatial demo with MongoDB    
    
spring:
    application:
        name: spring-geospatial-mongodb
    main:
        logStartupInfo: false
    data:
        mongodb:
            database: geotest
            host: localhost
            port: 27017
    devtools:
        restart:
            enabled: true
            additional-paths: src            
        
        

